# Generated by Django 5.2.4 on 2025-08-14 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mailings", "0002_initial"),
        ("newsletters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletters",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mailings.mailings"
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="recipient",
            field=models.ManyToManyField(to="mailings.mailingrecipient"),
        ),
        migrations.AddField(
            model_name="mailingattempt",
            name="mailings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="newsletters.newsletter",
            ),
        ),
    ]
